"""add arcane onboarding fields

Revision ID: 896be4089168
Revises: c4d9e8f20323
Create Date: 2026-09-12 22:58:02.632932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896be4089168'
down_revision: Union[str, Sequence[str], None] = 'c4d9e8f20323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profession', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('grand_goal', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'grand_goal')
    op.drop_column('users', 'profession')
    # ### end Alembic commands ###
